server:
  port: 8083

spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      start:
        log-level: info
        command: up
      stop:
        command: down
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/dl_manager?serverTimezone=Europe/Moscow
    username: root
    password: 666666

jwt:
  password:
    encoder:
      secret: 3ef45f2e73ffecccffbebafe18ddb3e323b66b4ecbfcfa8ef8a8f994f606f659
      iteration: 64
      keyLength: 256
  secret: 619a6f12e315d17239d4414f9fe1abf6f1a890713086b34d470446d139a25b74
  expiration: 3600
  issuer: dl_manager
aws:
  accesskey: YCAJEp2wHyggJ_GqDqp-x-jrN
  secretkey: YCPAghtWY_l3ErNA-AmD9Lzv0ymU6ynOboFnQdW3
  region: ru-central1
  s3BucketName: springfluxr2dbc
  multipartMinPartSize: 5242880
  endpoint: https://storage.yandexcloud.net/